import { describe, it, expect } from "vitest";
// @ts-expect-error node:fs carries no types here: the src project is kept
// DOM-only on purpose, and vite.config.ts reaches for Node the same way.
import { readFileSync } from "node:fs";
import {
  A4,
  DEFAULT_MARGIN_MM,
  DEFAULT_PAGE,
  LETTER,
  buildPagedCss,
  mmToInches,
  mmToPx,
  pageMetrics,
  paperById,
  paperByName,
  marginByName,
  MIN_DOCUMENT_MARGIN_MM,
  MAX_DOCUMENT_MARGIN_MM,
} from "./pageSetup";

const read = (name: string) => readFileSync(new URL(name, import.meta.url), "utf8");

describe("the page geometry", () => {
  it("converts millimetres to CSS pixels at 96 dpi", () => {
    // The web's fixed conversion, not a screen's. 25.4 mm is one inch.
    expect(mmToPx(25.4)).toBe(96);
    expect(mmToPx(210)).toBe(794);
    expect(mmToInches(25.4)).toBeCloseTo(1, 10);
  });

  it("gives A4 the content box the layout passes have always used", () => {
    // 605 and 934 are the numbers `previewRenderer` carried as constants, and
    // they are what the table-fitting and heading-grouping decisions compare
    // against. This is the assertion that says the arithmetic here reproduces
    // them rather than approximating them.
    expect(DEFAULT_PAGE.contentWidthPx).toBe(605);
    expect(DEFAULT_PAGE.contentHeightPx).toBe(934);
  });

  it("makes a landscape page as wide as a portrait one is tall", () => {
    // The same 247 mm, so the same number. As two hand-written constants they
    // disagreed by a pixel — 934 for the height, 933 for the landscape width.
    expect(DEFAULT_PAGE.landscapeContentWidthPx).toBe(DEFAULT_PAGE.contentHeightPx);
    expect(DEFAULT_PAGE.landscapeContentWidthPx).toBe(934);
  });

  it("takes the margin off both sides", () => {
    const wide = pageMetrics(A4, 0);
    expect(wide.contentWidthPx).toBe(mmToPx(210));
    expect(wide.contentHeightPx).toBe(mmToPx(297));
  });

  it("writes the margin the way a stylesheet spells it", () => {
    expect(DEFAULT_PAGE.marginCss).toBe("2.5cm");
    expect(pageMetrics(A4, 20).marginCss).toBe("2cm");
  });
});

describe("the stylesheets agree with it", () => {
  /*
   * The point of the module. These files each state the page in their own
   * units, and nothing has ever compared them to one source — only to each
   * other, and only for the table metrics. A margin changed in one and not the
   * others is a document measured against one page and printed on another.
   */

  it("paged.css states no page of its own for this module to disagree with", () => {
    /*
     * Inverted on purpose, and it used to assert the opposite.
     *
     * The page is generated by `buildPagedCss` and put in front of the file.
     * The file stating a size or a page margin as well would be two sources
     * for one sheet, which is the drift this whole block exists to catch —
     * and it is how the previous arrangement failed: the geometry lived in
     * the file, was rewritten by matching text, and the match stopped working
     * the moment a build minified it.
     */
    const css = read("./paged.css");
    expect(css).not.toMatch(/^\s*size:/m);
    expect(css).not.toMatch(/^\s*margin:\s*[\d.]+(cm|mm|in);/m);
  });

  /**
   * The paper's own dimensions as a stylesheet spells them: `21cm`, `29.7cm`.
   *
   * Derived, not written out. Written out, these assertions would keep passing
   * while the module and the stylesheets described different sheets — which is
   * the one thing they exist to catch.
   */
  const cm = (mm: number) => `${Number((mm / 10).toFixed(2))}cm`;

  it("the offscreen measuring container takes its width from the page", () => {
    // It used to state `21cm` outright. Preview now sets `--doc-sheet-width`
    // from the metrics, so a Letter document is measured against a Letter
    // sheet — and the literal left here is the fallback, which still has to be
    // the paper this file was written for.
    const css = read("./preview/document-view.css");
    expect(css).toMatch(
      new RegExp(`width:\\s*var\\(--doc-sheet-width,\\s*${cm(A4.widthMm)}\\)`),
    );
  });

  it("the HTML export builds its frame from the page rather than stating it", () => {
    // The assertion that survives templating: no hand-written sheet size may
    // remain, because a document on Letter would then be framed as A4.
    const source = read("./exportHtml.ts");
    expect(source).toContain("max-width: ${metrics.widthCss}");
    expect(source).toContain("min-height: ${metrics.heightCss}");
    expect(source).toContain("padding: ${metrics.marginCss}");
    // A physical length, specifically. `max-width: 100%` is not a sheet size
    // and there are three of them in that stylesheet.
    expect(source).not.toMatch(/max-width:\s*\d+(\.\d+)?(cm|mm|in)\b/);
  });
});

describe("the defaults", () => {
  it("are A4 with 2.5 cm, which is what the project ships", () => {
    expect(DEFAULT_PAGE.paper).toBe(A4);
    expect(DEFAULT_MARGIN_MM).toBe(25);
  });
});

describe("Letter", () => {
  it("is 8.5 by 11 inches, in millimetres", () => {
    expect(LETTER.widthMm).toBeCloseTo(mmToInches(LETTER.widthMm) * 25.4, 6);
    expect(mmToInches(LETTER.widthMm)).toBeCloseTo(8.5, 3);
    expect(mmToInches(LETTER.heightMm)).toBeCloseTo(11, 3);
  });

  it("is wider than A4 and shorter, which is the whole problem", () => {
    // Not a detail of the print dialog: a sheet laid out for one and printed
    // on the other does not shift, it spills.
    const letter = pageMetrics(LETTER);
    expect(letter.contentWidthPx).toBeGreaterThan(DEFAULT_PAGE.contentWidthPx);
    expect(letter.contentHeightPx).toBeLessThan(DEFAULT_PAGE.contentHeightPx);
  });

  it("is what a stored id resolves to, and anything else is A4", () => {
    expect(paperById("letter")).toBe(LETTER);
    expect(paperById("a4")).toBe(A4);
    expect(paperById("foolscap")).toBe(A4);
    expect(paperById(undefined)).toBe(A4);
  });
});

describe("the paper a document names", () => {
  it("reads the spellings the two toolchains use", () => {
    // Pandoc's `papersize:`, and LaTeX's `\documentclass` options, which is
    // where a Markdown writer is likely to have met the word.
    expect(paperByName("a4")).toBe(A4);
    expect(paperByName("letter")).toBe(LETTER);
    expect(paperByName("a4paper")).toBe(A4);
    expect(paperByName("letterpaper")).toBe(LETTER);
    expect(paperByName("us-letter")).toBe(LETTER);
  });

  it("ignores case and the space around it", () => {
    expect(paperByName("  A4 ")).toBe(A4);
    expect(paperByName("Letter")).toBe(LETTER);
    expect(paperByName("US Letter")).toBe(LETTER);
  });

  it("answers nothing for what it does not know, rather than A4", () => {
    /*
     * The difference between this and `paperById`, and the reason both exist.
     * Nothing here means "the document did not choose", and the reader's
     * preference is what then decides. Answering A4 would let a typo in a
     * document overrule a setting the reader made on purpose.
     */
    expect(paperByName("foolscap")).toBeNull();
    expect(paperByName("a5")).toBeNull();
    expect(paperByName("paper")).toBeNull();
    expect(paperByName("")).toBeNull();
    expect(paperByName(null)).toBeNull();
    expect(paperByName(undefined)).toBeNull();
  });
});

describe("the margin a document names", () => {
  it("reads the units a document is likely to state it in", () => {
    expect(marginByName("25mm")).toBe(25);
    expect(marginByName("2.5cm")).toBe(25);
    expect(marginByName("1in")).toBe(25.4);
    expect(marginByName("36pt")).toBe(12.7);
  });

  it("reads a bare number as millimetres", () => {
    // Which is what `pageMetrics` speaks, and what the preference stores.
    expect(marginByName("30")).toBe(30);
  });

  it("ignores case and the space around and inside it", () => {
    expect(marginByName("  2.5 CM ")).toBe(25);
    expect(marginByName("1 IN")).toBe(25.4);
  });

  it("answers nothing for a width outside the range that still prints", () => {
    /*
     * The folio and the running title are `@page` margin boxes and live in
     * this white space. A document that asks for 2 mm is asking for a page
     * with nowhere to put its number, and the reader's preference is a better
     * answer than a page that loses it.
     */
    expect(marginByName("2mm")).toBeNull();
    expect(marginByName("0")).toBeNull();
    expect(marginByName("80mm")).toBeNull();
    expect(marginByName(`${MIN_DOCUMENT_MARGIN_MM}mm`)).toBe(MIN_DOCUMENT_MARGIN_MM);
    expect(marginByName(`${MAX_DOCUMENT_MARGIN_MM}mm`)).toBe(MAX_DOCUMENT_MARGIN_MM);
  });

  it("answers nothing for what it cannot read", () => {
    expect(marginByName("wide")).toBeNull();
    expect(marginByName("1em")).toBeNull();
    expect(marginByName("2.5cm 3cm")).toBeNull();
    expect(marginByName("-10mm")).toBeNull();
    expect(marginByName("")).toBeNull();
    expect(marginByName(null)).toBeNull();
    expect(marginByName(undefined)).toBeNull();
  });
});

describe("building the page in front of paged.css", () => {
  const css = read("./paged.css");

  /**
   * The stylesheet as the built application receives it.
   *
   * `?inline` is served verbatim by Vite in development and minified on
   * build, and the difference is not cosmetic: the previous version of
   * `buildPagedCss` rewrote three line-anchored patterns, which matched
   * nothing once the file was one long line, so every built copy of the
   * application threw and drew no pages at all. Every test here runs against
   * both forms, because only one of them is what ships.
   */
  const minified = (text: string) =>
    text
      .replace(/\/\*[\s\S]*?\*\//g, "")
      .replace(/\s*([{};:,])\s*/g, "$1")
      .replace(/;\}/g, "}")
      .trim();

  const forms: Array<[string, string]> = [
    ["as written", css],
    ["as built", minified(css)],
  ];

  for (const [name, sheet] of forms) {
    it(`states the default page, ${name}`, () => {
      const out = buildPagedCss(sheet, DEFAULT_PAGE);
      expect(out).toContain("size: A4;");
      expect(out).toContain("size: A4 landscape;");
      expect(out).toContain(`margin: ${DEFAULT_PAGE.marginCss};`);
      // And the stylesheet itself is still in there, boxes and all.
      expect(out).toContain("@top-center");
    });

    it(`states Letter and a wider margin, ${name}`, () => {
      const out = buildPagedCss(sheet, pageMetrics(LETTER, 35));
      /*
       * Read off the generated part alone.
       *
       * The stylesheet behind it is full of `font-size` and element margins,
       * and a pattern loose enough to reach into it would be answering a
       * different question — the first version of this test counted
       * twenty-one sizes and most of them were type.
       */
      const generated = out.slice(0, out.length - sheet.length);
      // Both sizes, because the landscape one is the easy one to forget and
      // forgetting it prints wide tables on a different sheet from the rest.
      const sizes = [...generated.matchAll(/size:\s*([^;]+);/g)].map((m) => m[1]);
      expect(sizes).toEqual(["Letter", "Letter landscape"]);
      const margins = [...generated.matchAll(/margin:\s*([^;]+);/g)].map((m) => m[1]);
      expect(margins).toEqual(["3.5cm", "3.5cm"]);
    });
  }

  it("leaves nothing in paged.css for anyone to write a page size back into", () => {
    /*
     * The other half of the fix, and the half that keeps it fixed. As long as
     * the file states no page geometry at all there is no text to match, no
     * formatting to depend on, and nothing for a build step to reformat out
     * from under the code.
     */
    const pageBlocks = [...css.matchAll(/@page[^{]*\{/g)];
    expect(pageBlocks.length, "paged.css should still declare its margin boxes").toBeGreaterThan(0);
    expect(css).not.toMatch(/^\s*size:/m);
    expect(css).not.toMatch(/^\s*margin:\s*[\d.]+(cm|mm|in);/m);
  });

  it("works on an empty stylesheet, which is what vitest sees", () => {
    // `./paged.css?inline` is "" under vitest, and the page still has to be
    // stated: the rules are generated, not found.
    expect(buildPagedCss("", pageMetrics(LETTER))).toContain("size: Letter;");
  });
});
